# -*- coding: utf-8 -*-

from __future__ import absolute_import, print_function, unicode_literals

from rdvhome.gpio import GPIO

import os
import tempfile

"""
Django settings for rdvhome project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g&z@dt4o)&$j)2+e*p@1)9!=!&moja1%tz+g+0tia3y+$u+fa*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not GPIO

ALLOWED_HOSTS = ["*"]
APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin',
    #'django.contrib.auth',
    #'django.contrib.contenttypes',
    'django.contrib.sessions',
    #'django.contrib.messages',
    #'django.contrib.staticfiles',
    'rdvhome'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    #'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    #'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    #'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rdvhome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                #'django.template.context_processors.debug',
                #'django.template.context_processors.request',
                #'django.contrib.auth.context_processors.auth',
                #'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': tempfile.gettempdir()
    },
}

WSGI_APPLICATION = 'rdvhome.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

AWS_DEFAULT_REGION    = "eu-central-1"
AWS_ACCESS_KEY_ID     = "AKIAIYEFWRRN7LSZFWSQ"
AWS_SECRET_ACCESS_KEY = "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"
AWS_HEADERS = {
    'Expires': 'Thu, 15 Apr 2030 20:00:00 GMT',
    'Cache-Control': 'max-age=2592000',
}

AWS_IS_GZIPPED = True
GZIP_CONTENT_TYPES = (
    'application/javascript',
    'application/x-javascript',
    'application/json',
    'application/pdf',
    'application/postscript',
    'application/vnd.iccprofile',
    'application/vnd.ms-fontobject',
    'application/x-font-ttf',
    'application/x-font-woff',
    'application/x-font-woff2',
    'image/bmp',
    'image/svg+xml',
    'image/vnd.adobe.photoshop',
    'text/css',
    'text/html',
    'text/less',
    'text/plain',
)

AWS_DEPLOY_URL = "https://rdvhome.s3.eu-central-1.amazonaws.com"

MQTT_CHANNEL_COMMAND = "c-63HhqFG9QoKRbq47q0D48N"
MQTT_CHANNEL_STATUS  = "s-63HhqFG9QoKRbq47q0D48N"

MQTT_BROKER_URL = "iot.eclipse.org"
MQTT_BROKER_PORT = 1883
MQTT_BROKER_PORT_WEBSOCKET = 8000
MQTT_BROKER_SSL = False
MQTT_BROKER_PASSWORD = None
MQTT_BROKER_USERNAME = None

#MQTT_BROKER_URL = "m21.cloudmqtt.com"
#MQTT_BROKER_PORT = 16494
#MQTT_BROKER_PORT_WEBSOCKET = 36494
#MQTT_BROKER_PASSWORD = '0aeZc50ixVbT'
#MQTT_BROKER_USERNAME = 'owflekio'
#MQTT_BROKER_SSL = True